*SECTION_SHELL_TITLE
rod
$#   secid    elform      shrf       nip     propt   qr/irid     icomp     setyp
         2        13       1.0         0       3.0         0         0         1
$#      t1        t2        t3        t4      nloc     marea      idof    edgset
       0.0       0.0       0.0       0.0       1.0       0.0       0.0         0
*MAT_ELASTIC
$#     mid        ro         e        pr        da        db  not used        
         2  &DENSITY &YOUNGMOD  &POISSON       0.0       0.0       0.0
